### ISSUE TITLE
Some languages have almost no coverage

### ISSUE THREAD

**Issue by LinguList** [lexibank/lionnetyotonahua#6]
```python
from lingpy import *
from tabulate import tabulate
wl = Wordlist("edictor/yotonahua.tsv")
print(tabulate([[x, y] for x, y in wl.coverage().items()], headers=["language", "forms"]))
```

**Comment by LinguList** [comment]
| language          |   forms |
|:------------------|--------:|
| EudeveNorth       |     269 |
| EudeveSouth       |      23 |
| Mayo              |     255 |
| Opata             |     249 |
| ProtoSonoran      |     362 |
| ProtoTepiman      |     132 |
| SonoraPimaBajo    |      48 |
| TarahumaraCentral |     311 |
| TepehuanNorth     |      14 |
| TepehuanSouth     |       4 |
| TohonoOdam        |      49 |
| Tubar             |     184 |
| WarihioHighland   |     282 |
| WarihioLowland    |     189 |
| Yaqui             |     241 |

**Comment by LinguList** [comment]
If we check these counts, we can see that TepehuanNorth is not present, neither TepehuanSouthm, as is EudeveSouth, and I'd also say that TohonoOdam is not worth being listed here. With so spurious amounts, it is not possible to get realistic correspondences, so they only make the analysis muddy.

**Comment by LinguList** [comment]
In brief: all languages with < 100 forms should be discarded.

**Comment by LinguList** [comment]
@Maunus, as you have the file, etc., maybe you could also check that these numbers are about right?

**Comment by Maunus** [comment]
I think it would be a shame to discard them. I just checked the small languages, and there are some cases in which they provide the only member of a cognate for a given subgroup, or where they attest the presence of a particular sound segment in the cognate that s not present in the others.  
Would it be a possibility to just collapse them into a single node so that EN/ES are treated as a single entity?
By discarding Pima Bajo, Tohono O'dam and the two Tepehuán varieties we'd lose coverage of the Tepiman branch entirely - we'd only have Bascom's reconstructions. Another solution might be to add data for Tepehuán varieties and Tohono O'odam since there are now better sources available than when Lionnet was writing.

**Comment by LinguList** [comment]
I think we need to be realistic about what we can do with this dataset. As the coverage for some languages is ridiculously small, a neogrammarian approach requires to discard the languages with < 100 forms. Keeping them in the data is possible, but this skews the results, it adds noise to sound correspondences, and makes it only more difficult to really test the cognates by Lionnet.

**Comment by LinguList** [comment]
Collapsing is also not an option, as this is even worse for sound correspondences.

**Comment by LinguList** [comment]
What I'd suggest to do is: for an initial analysis that tests Lionnet's cognates and refines them, one needs to ignore the languages with low coverage. One should then also conclude and say that Lionnet failed to provide sufficient data for any claims on their affiliation or the reconstruction of the proto-language.

**Comment by LinguList** [comment]
But what one can do is then using additional data from other sources to expand them into a new analysis that no longer is Lionnet's analysis, but a new result that should also be published as such.

**Comment by LinguList** [comment]
And as a compromise, we CAN add additional entries in prose form to the proto-form. That would not allow us to take them as evidence for any computer-assisted analysis, but it would allow interested scholars to read about this very part of the analysis.

**Comment by LinguList** [comment]
So we'd add an entry "ReflexesInSource" as a column to the data. This would contain all reflexes in the original source, which were parsed as such.

**Comment by Maunus** [comment]
We will eventually need to add the Cora, Huichol and Nahuatl data to this one as well, in one big database - and I guess we can add better data for Tepehuan and O'odam as well at that time.

**Comment by LinguList** [comment]
@Maunus, I have a new solution for the lack of some languages: We leave the languages in the sample, but we do exclude them from analyses if we want to make them.

Later, when it comes to merging datasets, you can then select, which ones to use.
